# Generated by Django 2.1.15 on 2020-04-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
    ]
