# Generated by Django 2.1.15 on 2020-03-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_chapter_description'),
        ('quiz', '0002_quiz_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter'),
        ),
    ]
