# Generated by Django 2.1.15 on 2020-04-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200408_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
