# Generated by Django 2.1.15 on 2020-03-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200324_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter'),
        ),
    ]
