# Generated by Django 2.1.15 on 2020-06-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(default=' ', max_length=1000)),
                ('content', models.TextField(max_length=10000)),
                ('line1', models.CharField(blank=True, max_length=1000, null=True)),
                ('line2', models.CharField(blank=True, max_length=1000, null=True)),
                ('line3', models.CharField(blank=True, max_length=1000, null=True)),
                ('line4', models.CharField(blank=True, max_length=1000, null=True)),
                ('line5', models.CharField(blank=True, max_length=1000, null=True)),
                ('line6', models.CharField(blank=True, max_length=1000, null=True)),
                ('line7', models.CharField(blank=True, max_length=1000, null=True)),
                ('line8', models.CharField(blank=True, max_length=1000, null=True)),
                ('line9', models.CharField(blank=True, max_length=1000, null=True)),
                ('line10', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('correct_answers', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
