# Generated by Django 2.1.15 on 2020-04-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='line1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line10',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='line9',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
