# Generated by Django 2.1.15 on 2020-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='chapterData',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='users',
        ),
    ]
