# Generated by Django 2.1.15 on 2020-07-06 08:01

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200615_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.upload_path),
        ),
    ]
