# Generated by Django 2.1.15 on 2020-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200402_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='users',
        ),
        migrations.RemoveField(
            model_name='chapterdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
    ]
