# Generated by Django 2.1.15 on 2020-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200131_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
