# Generated by Django 2.1.15 on 2020-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_chapter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
