# Generated by Django 2.1.15 on 2020-04-03 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20200403_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(null=True, through='article.ChapterData', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
