# Generated by Django 2.1.15 on 2020-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200403_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='chapterData',
        ),
    ]
