# Generated by Django 2.1.15 on 2020-03-27 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, through='article.ChapterUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
