# Generated by Django 2.1.15 on 2020-03-27 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200327_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(blank=True, through='article.ChapterUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
