# Generated by Django 2.1.15 on 2020-04-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200403_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='chapterData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ChapterData'),
        ),
    ]
