# Generated by Django 2.1.15 on 2020-04-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_userdata_chapterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='chapterData',
        ),
        migrations.AddField(
            model_name='chapterdata',
            name='userData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.UserData'),
        ),
    ]
