# Generated by Django 2.1.15 on 2020-04-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200403_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='users',
        ),
        migrations.RemoveField(
            model_name='chapterdata',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapterdata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ChapterData'),
        ),
    ]
