# Generated by Django 2.1.15 on 2020-03-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ChapterUser')),
            ],
        ),
    ]
