# Generated by Django 2.1.15 on 2020-04-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200404_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapterdata',
        ),
        migrations.AddField(
            model_name='chapterdata',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Chapter'),
        ),
    ]
