# Generated by Django 2.1.15 on 2020-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200327_0951'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chapters',
            field=models.ManyToManyField(through='article.ChapterUser', to='article.Chapter'),
        ),
    ]
