# Generated by Django 2.1.15 on 2020-04-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=' ', max_length=200)),
                ('lastName', models.CharField(default=' ', max_length=200)),
                ('company', models.CharField(default=' ', max_length=200)),
                ('position', models.CharField(default=' ', max_length=200)),
                ('country', models.CharField(default=' ', max_length=200)),
                ('facebook', models.CharField(default=' ', max_length=200)),
                ('twitter', models.CharField(default=' ', max_length=200)),
                ('instagram', models.CharField(default=' ', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
