# Generated by Django 2.1.15 on 2020-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200616_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userData',
        ),
        migrations.AddField(
            model_name='userdata',
            name='company',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='facebook',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='firstName',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='instagram',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastName',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='position',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='twitter',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
