# Generated by Django 2.1.15 on 2020-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200616_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='instagram',
            new_name='reddit',
        ),
    ]
