# Generated by Django 2.1.15 on 2020-04-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200403_1236'),
        ('user', '0003_auto_20200402_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ChapterData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ChapterData'),
        ),
    ]
