# Generated by Django 2.1.15 on 2020-04-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_chapterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ChapterData',
        ),
    ]
